## Import Libraries

In [2]:
import numpy as np
import pandas as pd

## Version

In [3]:
pd.__version__

'2.3.1'

## Data work

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [5]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [6]:
df.shape ##2160 records 

(2160, 12)

In [10]:
df['Brand'].unique() #27 unique brands

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [9]:
df.isnull().sum() # storage type, #GPU, screen columns - 3

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [12]:
df[df['Brand'] == 'Dell']['Final Price'].max() #3936 

np.float64(3936.0)

In [14]:
df['Screen'].mode() #15.6 is the median  #15.6 is the mode 

0    15.6
Name: Screen, dtype: float64

In [15]:
df['Screen'].fillna(df['Screen'].mode()[0], inplace = True)

/tmp/ipykernel_11405/2659933906.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Screen'].fillna(df['Screen'].mode()[0], inplace = True)


In [16]:
df['Screen'].mode() #15.6 again 

0    15.6
Name: Screen, dtype: float64

In [17]:
df['Screen'].median() #15.6

np.float64(15.6)

In [18]:
df_final = df[df['Brand'] == 'Innjoo']

In [20]:
df_final_cols = df_final[['RAM','Storage','Screen']]

In [21]:
df_final_cols

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [22]:
df_numpy = df_final_cols.to_numpy()

In [23]:
df_numpy

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [24]:
df_numpy_T = df_numpy.T

In [25]:
df_numpy_T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [27]:
df_mult = np.dot((df_numpy_T),(df_numpy))

In [29]:
df_inv = np.linalg.inv(df_mult)

In [30]:
df_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [31]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [32]:
res1 = np.dot(df_inv,df_numpy_T)
w = np.dot(res1,y)

In [33]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [34]:
sum1 = np.sum(w)

In [35]:
sum1 #91.30 is the sum 

np.float64(91.2998806299555)